In [ ]:
#Convert the given list into a numpy array and replace the odd elements with-2
import numpy as np

lst = [[1,2,3],
       [4,5,6],
       [7,8,9]]
 
arr = np.array(lst)
odd_values = (arr%2 == 1)
arr[odd_values] = -2
print("Old Array Without Numpy:")
print(lst)
print("New Array With Numpy:")
print(arr)


Old Array Without Numpy:
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
New Array With Numpy:
[[-2  2 -2]
 [ 4 -2  6]
 [-2  8 -2]]


In [ ]:
#In the numpy array given below print all the elements ranging from 8 to 15
import numpy as np
arr = [1,2,3,4,5,8,9,10,12,22,32,54,99,6,7]
new_arr = sorted(arr)
i = new_arr[7]
for i in range(7,11):
  print(new_arr[i])

8
9
10
12


In [ ]:
#Create a 3*3 narray that includes numbers from 1 to 9 and swap columns 1 and 2
my_array = np.arange(1,10).reshape(3, 3)

my_array[:, [1, 0]] = my_array[:, [0, 1]]

print("After swapping arrays first column and second column:")
print(my_array)


After swapping arrays first column and second column:
[[2 1 3]
 [5 4 6]
 [8 7 9]]


In [ ]:
#In the given numpyarray replace the NaN values with the average of columns
import numpy as np
nparr= np.array([[1.3, 2.5, 3.6, np.nan], [2.6, 3.3, np.nan, 5.5], [2.1, 3.2, 5.4, 6.5]])
print("Old Array: ")
print(nparr)
print("New Array With Nan Value Replaced: ")
print(np.nan_to_num(nparr, nan=np.nanmean(nparr)))

Old Array: 
[[1.3 2.5 3.6 nan]
 [2.6 3.3 nan 5.5]
 [2.1 3.2 5.4 6.5]]
New Array With Nan Value Replaced: 
[[1.3 2.5 3.6 3.6]
 [2.6 3.3 3.6 5.5]
 [2.1 3.2 5.4 6.5]]


In [ ]:
#For the nump yarray given below perform the following operation
import numpy as np
arr = [[2,4,6],[1,3,5]]
arr_2d = np. reshape(new_arr, (2, 3))
new_arr = sorted(arr_2d, key = lambda x : x[0], reverse=False)
print(arr_2d)



[[1 3 5]
 [2 4 6]]
